spring.application.name=minilog

server.port=8400

#springdoc.api-docs.enabled=false
#springdoc.swagger-ui.enabled=false

# JDBC Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JDBC Oracle 19C
#spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl

# JDBC Oracle 21XE
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE

spring.datasource.username=ONBOARDING_DEV
spring.datasource.password=123456

# Hibernate ì¤ì  ì¶ê°
# ì´ì íê²½ììë noneì´ë validate ì¬ì©
# ê°ë° íê²½ììë createì´ë update ì¬ì©
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ë°ì´í°ë¥¼ ê°ì ¸ì¬ ë í ë²ì ê°ì ¸ì¤ë ì
spring.jpa.properties.hibernate.jdbc.fetch_size=1

# JWT Token Setting
# 테스트를 위한 하드코딩 -> 차후 변경예정
jwt.secret=lPBW+vi2rF6Mw+nnqlZhAzGJXKWct7zLrfDG6ZSBC1M=


# View Resolver setting
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp