spring.application.name=minilog

server.port=8400

# 운영 환경에서 배포시(사용자 접근 불가)
#springdoc.api-docs.enabled=false
#springdoc.swagger-ui.enabled=false

# JDBC 설정 추가
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:orcl
spring.datasource.username=ONBOARDING_DEV
spring.datasource.password=123456

# Hibernate 설정 추가
# 운영 환경에서는 none이나 validate 사용
# 개발 환경에서는 create이나 update 사용
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 데이터를 가져올 때 한 번에 가져오는 수
spring.jpa.properties.hibernate.jdbc.fetch_size=1

# View Resolver setting
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp